### ISSUE TITLE
cant run main.py

### ISSUE THREAD

**Issue by ghandi2001** [yujianke100/GFDN#2]
hello there, i ran all that commands but i have an error in last command

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from abcore_data import get_abcore_data
  File "/home/sa/gfdn/abcore_data.py", line 1, in <module>
    import pyabcore
  File "/home/sa/gfdn/pyabcore.py", line 15, in <module>
    import _pyabcore
ModuleNotFoundError: No module named '_pyabcore'

thanks for helping.

**Comment by yujianke100** [comment]
Hi,
Please check the third and fourth steps in the readme.
If the environment is installed correctly, it will print two sets of boolean lists.

**Comment by ghandi2001** [comment]
Please check this image

**Comment by ghandi2001** [comment]
![Capture](https://github.com/yujianke100/GFDN/assets/72333196/adf13316-b7e1-4dec-8b74-0c8bd56f0578)

**Comment by ghandi2001** [comment]
I received this arrays but in python main.py i have an error.

**Comment by yujianke100** [comment]
It seems that the command cp meets some trouble. You can try to delete the pyabcore.py in the root path and cp the new one from `queryopt` or re-clone the code and build it from the beginning.

**Comment by ghandi2001** [comment]
![image](https://github.com/yujianke100/GFDN/assets/72333196/a07534cf-ea52-4dfe-ac05-33373ed8ecd0)
I'm still getting this error 😮

**Comment by yujianke100** [comment]
cp ./_pyabcore* pyabcore.py ../

**Comment by ghandi2001** [comment]
![image](https://github.com/yujianke100/GFDN/assets/72333196/e5932127-a4c5-4bc5-9bfc-009d60899792)
🤕

**Comment by ghandi2001** [comment]
nothing changed ... 😖

**Comment by yujianke100** [comment]
cd ./queryopt && cp ./_pyabcore* pyabcore.py ../
Please understand what I want to express instead of just run that command....

**Comment by ghandi2001** [comment]
thank you my friend, love you.
