### ISSUE TITLE
P||Q

### ISSUE THREAD

**Issue by QQQQQQBY** [yujianke100/GFDN#3]
Use P and Q matrices to increase the similarity between similar instances and reduce the similarity between different instances. Is there any specific literature reference for this scheme design? Or how did you cleverly design this approach to optimize?

Looking forward to your reply.

**Comment by yujianke100** [comment]
Are you referring to the step where we concatenate the information extracted using the (alpha, beta)-core algorithm with the original attributes? To our knowledge, we are the first to do this. However, prior approaches follow a similar idea of using information obtained from the WL algorithm as attributes for downstream tasks, as demonstrated in 'Weisfeiler and Leman go sparse: Towards scalable higher-order graph embeddings.'

**Comment by QQQQQQBY** [comment]
![pq](https://github.com/yujianke100/GFDN/assets/110973703/70575fd5-f47a-4268-896c-3c2fe087803a)
How is this part designed? I don't understand the reason why this part is so designed. Do you have specific reference to the paper? Looking forward to your reply.

**Comment by yujianke100** [comment]
[71] Visualizing Data using t-SNE

**Comment by QQQQQQBY** [comment]
Thanks~
